### ISSUE TITLE
back: link roles to users in User Service

### ISSUE THREAD

**Issue by codegold79** [OpenEugene/openboard#79]
RoleIDs are not stored in the user table, nor is there a joint table that links user IDs and roleIDs. Consider these as well as other alternatives for linking users and roles.

**Comment by daved** [comment]
AC
- [ ] Create join table for users to have multiple roles
- [ ] Update relevant migration file(s)
- [ ] Ensure the user message contains the role ids

*It's likely that we'll discuss whether to make multiple queries or a single query with fancy structure handling in order to hydrate a user and the related role data collection.

**Comment by daved** [comment]
Closed by #86
